apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "accusation.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "accusation.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "accusation.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "accusation.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          env:
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.env.configMap.name }}
                  key: log-level
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.env.configMap.name }}
                  key: db-host
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.secret.name }}
                  key: db-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.secret.name }}
                  key: db-password
            - name: MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.secret.name }}
                  key: mail-username
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.secret.name }}
                  key: mail-password
  strategy:
    blueGreen:
      activeService: {{ include "accusation.fullname" . }}
      previewService: {{ include "accusation.fullname" . }}-new
      autoPromotionEnabled: true
