apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "front.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{ .Values.selectorLabels }}
  template:
    metadata:
      labels:
        app: {{ .Values.selectorLabels }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
          securityContext:
            privileged: {{ .Values.securityContext.privileged }}
  strategy:
    blueGreen:
      activeService: {{ include "accusation.fullname" . }}
      #previewService:
      autoPromotionEnabled: {{ .Values.blueGreen.autoPromotion }}
