# Default values for accusation.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: mungta

nameOverride: ""
fullnameOverride: review

selectorLabels: review

replicaCount: 1
revisionHistoryLimit: 2

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 30
  # targetMemoryUtilizationPercentage: 80

image:
  repository: mungtaregistry.azurecr.io/mungta/dev/review-service
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "12"

resources:
  requests:
    cpu: 200m
  limits:
    cpu: 500m

env:
  configMap:
    name: review-config
  secret:
    name: mungta-credentials

config:
  logLevel: debug
  dbHost: review-service-db.mysql.database.azure.com

livenessProbe:
  path: /actuator/health/liveness
  port: 8080
  initialDelaySeconds: 60
  periodSeconds: 60
readinessProbe:
  path: /actuator/health/readiness
  port: 8080
  initialDelaySeconds: 15
  periodSeconds: 60

securityContext:
  privileged: false

blueGreen:
  autoPromotion: true

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: ""
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
