apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.env.gatewayName }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: {{ .Values.service.port }}
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.env.gatewayName }}
  namespace: {{ .Values.namespace }}
spec:
  hosts:
    - "*"
  gateways:
    - {{ .Values.env.gatewayName }}
  http:
    - match:
        - uri:
            prefix: /api
      route:
        - destination:
            host: {{ .Values.istioIngress.gateway.host }}
            port:
              number: {{ .Values.istioIngress.gateway.port }}
    - route:
        - destination:
            host: {{ .Values.istioIngress.front.host }}
            port:
              number: {{ .Values.istioIngress.front.port }}
